#!/bin/bash

#color used by cower
NC="\033[0m"

BOLDRED="\033[1;31m"
BOLDGREEN="\033[1;32m"
BOLDBLUE="\033[1;34m"
BOLDWHITE="\033[1;37m"


printf "${BOLDWHITE}Checking Official Repos...${NC}\n"
updates=`checkupdates`
if [[ $updates == "" ]] ; then
    printf " official repos are up to date\n"
fi
for package in $updates ; do 
    localversion=`sudo pacman -Qi $package | grep "Version" | awk '{print $3}' -`
    remoteversion=`sudo pacman -Sy | pacman -Si $package | grep "Version" | awk '{print $3}' -`
    if [[ ${localversion} != ${remoteversion} ]] ; then 
        printf "${BOLDBLUE}::${NC} ${BOLDWHITE}${package}${NC}\t${BOLDRED}${localversion}${NC} -> ${BOLDGREEN}${remoteversion}${NC}\n"
    fi
done


printf "${BOLDWHITE}Checking AUR...${NC}\n"
aur=`cower --color=auto -u`
if [[ $aur == "" ]] ; then
    printf " aur is up to date\n"
fi

