#!/bin/bash

#color used by cower
NC="\033[0m"
BOLD="\033[1m"

BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
MAGENTA="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"
BOLDBLACK="\033[1;30m"
BOLDRED="\033[1;31m"
BOLDGREEN="\033[1;32m"
BOLDYELLOW="\033[1;33m"
BOLDBLUE="\033[1;34m"
BOLDMAGENTA="\033[1;35m"
BOLDCYAN="\033[1;36m"
BOLDWHITE="\033[1;37m"


printf "${BOLDWHITE}Checking Official Repos${NC}\n"
updates=`checkupdates`
if [[ $updates == "" ]] ; then
    printf "Officical Repos are ${BOLDGREEN}Up-To-Date${NC}\n"
fi
for package in $updates ; do 
    localversion=`sudo pacman -Qi $package | grep "Version" | awk '{print $3}' -`
    remoteversion=`sudo pacman -Sy | pacman -Si $package | grep "Version" | awk '{print $3}' -`
    if [[ ${localversion} != ${remoteversion} ]] ; then 
        printf "${BOLDBLUE}::${NC} ${BOLDWHITE}${package}${NC}\t${BOLDRED}${localversion}${NC} -> ${BOLDGREEN}${remoteversion}${NC}\n"
    fi
done


printf "${BOLDWHITE}Checking AUR${NC}\n"
aur=`cower --color=auto -u`
if [[ $aur == "" ]] ; then
    printf "AUR is ${BOLDGREEN}Up-To-Date${NC}\n"
fi

